### ISSUE TITLE
I want to contribute, but don't know to what

### ISSUE THREAD

**Issue by joms** [vinkla/awesome-fuse#2]
Hi! Great list!

I made a precompile-procedure with Gulp that compiles ES6 into ES5 and concatenates all the javascript into a single file, as Fuse likes it that way. I guess it belongs on your list, but I don't really know what category. Any suggestions?

I've posted it on https://gist.github.com/joms/6a653c0ab68f5460c052

**Comment by vinkla** [comment]
Hi @joms, thanks!

I'm glad that you want to help out. Maybe you could create a new repository with your code along with a readme describing what it is? Then we could create a new section called Open Source or something similar. What do you think? Sounds good?

**Comment by joms** [comment]
Sounds like a great idea! :) I'll respond here as soon as I've gotten myself around and done it. Thanks!

**Comment by vinkla** [comment]
:+1:

**Comment by joms** [comment]
Does this seem okey? :) https://github.com/joms/gulp-fuse

**Comment by vinkla** [comment]
Looks good :+1: Maybe we should add it to the Libraries list? What do you think?

**Comment by joms** [comment]
Nice! It feels weird as it not a library per say, but as I figure an "Open Source" category should contain Fuse-code only I agree at it could belong in the Libraries list.

**Comment by vinkla** [comment]
Maybe we should create a new one called "Tools".

**Comment by vinkla** [comment]
Do you want to make the pull request or do you want me to do add it?

**Comment by joms** [comment]
"Tools" is great! :+1: You can go ahead and add it-

**Comment by vinkla** [comment]
Done. Thanks!
