### ISSUE TITLE
Looking for a new maintainer!

### ISSUE THREAD

**Issue by vinkla** [vinkla/awesome-fuse#57]
I'm no longer an active member of the Fuse community. I'm stepping down as a maintainer of this awesome list. @kusma and the `fuse-compound` organization has kindly taking over the ownership of this repository. We're looking for a new maintainer to handle the pull requests and issues of this project. If you feel up to it, don't hesitate to comment on this issue!

**Comment by AndrewEQ** [comment]
Sure thing man, I'm in if the post is still open hehe
